### ISSUE TITLE
Something breaks my cache file, then exceptions are encountered

### ISSUE THREAD

**Issue by fawkesley** [reclosedev/requests-cache#11]
I haven't yet worked out what triggers this, but from time to time my my sqlite cache appears to break, after which all calls to requests.get fail with the exception below. Deleting the cache file obviously fixes the problem but that's not ideal! Have you seen this before?

```
Traceback (most recent call last):
  File "tool/main.py", line 188, in <module>
    main()
  File "tool/main.py", line 62, in main
    for xls_url in get_excel_urls(download_url(INDEX_URL)):
  File "tool/main.py", line 101, in download_url
    response = requests.get(url)
  File "/home/venv/local/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/home/venv/local/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/venv/local/lib/python2.7/site-packages/requests_cache/core.py", line 111, in request
    hooks, stream, verify, cert)
  File "/home/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/venv/local/lib/python2.7/site-packages/requests_cache/core.py", line 89, in send
    response, timestamp = self.cache.get_response_and_time(cache_key)
  File "/home/venv/local/lib/python2.7/site-packages/requests_cache/backends/base.py", line 64, in get_response_and_time
    if key not in self.responses:
  File "/home/venv/lib/python2.7/_abcoll.py", line 348, in __contains__
    self[key]
  File "/home/venv/local/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 171, in __getitem__
    return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
  File "/home/venv/lib/python2.7/copy_reg.py", line 50, in _reconstructor
    obj = base.__new__(cls, state)
TypeError: ('dict.__new__(CaseInsensitiveDict): CaseInsensitiveDict is not a subtype of dict', <function _reconstructor at 0x7fe49d3039b0>, (<class 'requests.structures.CaseInsensitiveDict'>, <type 'dict'>, {'Accept-Encoding': 'gzip, deflate, compress', 'Accept': '*/*', 'User-Agent': 'python-requests/1.2.0 CPython/2.7.4 Linux/3.8.0-23-generic'}))
```

**Comment by JWCook** [comment]
For reference: See also #102.
