### ISSUE TITLE
"Unsupported event specified" when using throttling example

### ISSUE THREAD

**Issue by chrahunt** [reclosedev/requests-cache#127]
When using the throttling example from the [docs](https://requests-cache.readthedocs.io/en/latest/user_guide.html#usage):

```
s.hooks = {'response': make_throttle_hook(0.1)}
```

requests (2.21.0) raises an exception on request:

```
Traceback (most recent call last):
  File "example.py", line 31, in <module>
    r = s.get('https://pypi.org/simple/')
  File "venv/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "venv/lib/python3.7/site-packages/requests_cache/core.py", line 132, in request
    **kwargs
  File "venv/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "venv/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "venv/lib/python3.7/site-packages/requests/models.py", line 323, in prepare
    self.prepare_hooks(hooks)
  File "venv/lib/python3.7/site-packages/requests/models.py", line 583, in prepare_hooks
    self.register_hook(event, hooks[event])
  File "venv/lib/python3.7/site-packages/requests/models.py", line 179, in register_hook
    raise ValueError('Unsupported event specified, with event name "%s"' % (event))
ValueError: Unsupported event specified, with event name "reponse"
```

Switching to the suggested method of hook registration (from [here](https://2.python-requests.org/en/master/user/advanced/#event-hooks)) worked:

```
s.hooks['response'].append(make_throttle_hook(0.1))
```

**Comment by JWCook** [comment]
Updated the documentation. Thanks for pointing this out!
