### ISSUE TITLE
TypeError with DbPickleDict initialization, depending on db location

### ISSUE THREAD

**Issue by pslacerda** [reclosedev/requests-cache#136]
This error happened unexpectedly:
```python
requests.get("https://www.rcsb.org/pdb/rest/sequenceCluster?cluster=95&structureId=2XY9.A")
```
```
Traceback (most recent call last):
  File "/home/pedro/anaconda3/envs/hotspots/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pedro/anaconda3/envs/hotspots/lib/python3.7/site-packages/requests/api.py", line 59, in request
    with sessions.Session() as session:
  File "/home/pedro/anaconda3/envs/hotspots/lib/python3.7/site-packages/requests_cache/core.py", line 208, in __init__
    **backend_options
  File "/home/pedro/anaconda3/envs/hotspots/lib/python3.7/site-packages/requests_cache/core.py", line 73, in __init__
    self.cache = backends.create_backend(backend, cache_name, backend_options)
  File "/home/pedro/anaconda3/envs/hotspots/lib/python3.7/site-packages/requests_cache/backends/__init__.py", line 63, in create_backend
    return registry[backend_name](cache_name, **options)
  File "/home/pedro/anaconda3/envs/hotspots/lib/python3.7/site-packages/requests_cache/backends/sqlite.py", line 28, in __init__
    self.responses = DbPickleDict(location + extension, 'responses', fast_save=fast_save)
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by reclosedev** [comment]
Can you show cache initialization code?

**Comment by JWCook** [comment]
I'm unable to reproduce this, but based on the traceback this should be easy to fix.
