### ISSUE TITLE
Issue with requests_cache.core.remove_expired_responses()

### ISSUE THREAD

**Issue by bkaplan1** [reclosedev/requests-cache#160]
I installed the python purpleair library which uses this command requests_cache.core.remove_expired_responses() and found it doesn't work.  

I tried it manually with a couple other request_cache commands and the 
 requests_cache.core.remove_expired_responses()
causes the following traceback.

Any ideas on what is going on?   The developer of purpleair is not having this problem.  Thanks

>> from datetime import timedelta
>>> import requests_cache
>>> requests_cache.install_cache(expire_after=timedelta(hours=1))
>>> requests_cache.core.remove_expired_responses()
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests_cache\core.py", line 287, in remove_expired_responses
    return requests.Session().remove_expired_responses()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests_cache\core.py", line 212, in __init__
    **backend_options
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests_cache\core.py", line 73, in __init__
    self.cache = backends.create_backend(backend, cache_name, backend_options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests_cache\backends\__init__.py", line 63, in create_backend
    return registry[backend_name](cache_name, **options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests_cache\backends\sqlite.py", line 28, in __init__
    self.responses = DbPickleDict(location + extension, 'responses', fast_save=fast_save)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests_cache\backends\storage\dbdict.py", line 62, in __init__
    with self.connection() as con:
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests_cache\backends\storage\dbdict.py", line 74, in connection
    con = sqlite.connect(self.filename)
sqlite3.OperationalError: unable to open database file
>>> requests_cache.install_cache('demo_cache')
>>>

**Comment by ReagentX** [comment]
I was able to replicate this by running `chmod 0 cache.sqlite`, so I suspect this is a ownership problem.

**Comment by JWCook** [comment]
Right, this is almost certainly a file permissions issue. Try specifying a location using the `cache_name` parameter, or make sure your user has write permissions to the directory you're running this from (since it will create the cache file in the current directory by default).

I'm going to close this issue for now, but please comment if you're still having problems and I'll reopen it.
