### ISSUE TITLE
remove_expired_responses() not working when global hook not installed

### ISSUE THREAD

**Issue by gjedeer** [reclosedev/requests-cache#163]
Test case:

```
import requests
import requests_cache

with requests_cache.enabled('issue'):
    print(requests.get('http://httpbin.org/uuid').text)

# This is a workaround - but it should not be needed in a module-level function I think
with requests_cache.enabled('issue'):
    requests_cache.remove_expired_responses()

requests_cache.remove_expired_responses()
```

```
{
  "uuid": "38096e23-7b64-44ed-b691-495266c6c34b"
}

Traceback (most recent call last):
  File "requests_cache_issue.py", line 10, in <module>
    requests_cache.remove_expired_responses()
  File "/home/andrzej/venv3/lib/python3.6/site-packages/requests_cache/core.py", line 287, in remove_expired_responses
    return requests.Session().remove_expired_responses()
AttributeError: 'Session' object has no attribute 'remove_expired_responses'

```

**Comment by JWCook** [comment]
Thanks for the reproducible example. This should be an easy fix.

**Comment by JWCook** [comment]
Done! The functions `get_cache(), `clear()`, and `remove_expired_responses()` are now safe to call if requests-cache is not installed.
