### ISSUE TITLE
AttributeError: 'DbPickleDict' object has no attribute '_local_context'

### ISSUE THREAD

**Issue by glensc** [reclosedev/requests-cache#433]
### The problem

requests cache can't load cache again:

```
  File "/Users/glen/MegaSync/scm/plex/PlexTraktSync/plex_trakt_sync/factory.py", line 44, in session
    session = CachedSession(trakt_cache)
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.9.7/lib/python3.9/site-packages/requests_cache/session.py", line 45, in __init__
    self.cache = init_backend(backend, cache_name, **kwargs)
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.9.7/lib/python3.9/site-packages/requests_cache/backends/__init__.py", line 100, in init_backend
    return BACKEND_CLASSES[backend](*args, **kwargs)
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.9.7/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 38, in __init__
    self.responses = DbPickleDict(
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.9.7/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 90, in __init__
    self.db_path = _get_db_path(db_path, use_temp)
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.9.7/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 243, in _get_db_path
    makedirs(dirname(db_path), exist_ok=True)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/glen/.cache/PlexTraktSync'
Exception ignored in: <function DbDict.__del__ at 0x1105b4c10>
Traceback (most recent call last):
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.9.7/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 146, in __del__
    self.close()
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.9.7/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 121, in close
    if getattr(self._local_context, 'con', None):
AttributeError: 'DbPickleDict' object has no attribute '_local_context'
```

### Expected behavior

Catch or ignore error, do not throw.

### Steps to reproduce the behavior

1. install requests cache 0.8.0 (i guess)
2. populate cache
3. use same cache on requests cache 0.7.4

### Workarounds

yes, nuke cache or upgrade package

### Environment

- requests-cache version: 0.7.4
- Python version: 3.9.7
- Platform: macOS

**Comment by glensc** [comment]
@JWCook I thought to report this, maybe you want to handle such errors gracefully again.

also, I see there mkdir EEXIST error, perhaps that should be handled too

**Comment by glensc** [comment]
Looks like I can't reproduce this anymore either. But at least you got some ideas and some fixes out of this.

**Comment by glensc** [comment]
Also, /Users/glen/.cache/PlexTraktSync was a symlink pointing to a directory that did not exist.

**Comment by glensc** [comment]
Oh, that is the actual reason. cache file needs to point inside a "directory" which is a symlink to a path that does not exist.

in my case:
```
rm -rf /Users/glen/.cache/PlexTraktSync
ln -s /tmp/definitely-does-not-exist /Users/glen/.cache/PlexTraktSync
```
