### ISSUE TITLE
session.cache_disabled() still hits sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by Avasam** [reclosedev/requests-cache#514]
### The problem
I'm hitting a lot of `sqlite3.OperationalError: database is locked` (which I'll ask for help/support for in a different issue). I thought I could simply catch and try again without cache, but using `with session.cache_disabled()` still throws a `database is locked` error

### Expected behavior
If the cache is disabled in current context, the current state of the database should not matter

### Steps to reproduce the behavior
Code snippet:
```py
session = CachedSession(
    expire_after=timedelta(days=1),
    allowable_codes=(200, 500),
    ignored_parameters=["status", "video-only", "embed"],
    backend=configs.cached_session_backend,  # None
    fast_save=True,
    use_temp=True)
session.mount("https://", HTTPAdapter(pool_maxsize=RATE_LIMIT + 1))  # 101
        [...]
        with nullcontext() if cached else session.cache_disabled():
            try:
                response = session.get(url, params=params, headers=headers)
            # TODO: Try to check for available space first (<=5%),
            # https://help.pythonanywhere.com/pages/DiskQuota
            # "disk I/O erro" when going over PythonAnywhere"s Disk Quota
            except OSError as error:
                session.cache.clear()
                print("Cleared cache in response to OSError:", error)
                response = session.get(url, params=params, headers=headers)
            # Note: This happens with LOTS of concurent requests
            # (probably any Seterra player, but dha is the latest that gave me issues)
            except OperationalError as error:
                print("Ignoring cache for this request because of OperationalError:", error)
                with session.cache_disabled():
                    response = session.get(url, params=params, headers=headers)
```

### Workarounds
I could use regular requests library in the mean time for those calls. I also need to figure out a better fix for my root issue.

### Environment
- requests-cache version: 0.7.3.dev0 AND 0.9.1
- Python version: 3.9
- Platform: Ubuntu 20.04.2 LTS

### Stacktrace
```py
Traceback (most recent call last):
File "/home/Avasam/mysite/backend/./services/utils.py", line 159, in get_request_cache_bust_if_disk_quota_exceeded
response = session.get(url, params=params, headers=headers)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/session.py", line 115, in request
cache_key=cache_key,
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/session.py", line 147, in send
return response
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/session.py", line 193, in _send_and_cache
cache_criteria = {
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/backends/base.py", line 97, in save_response
except (KeyError, *DESERIALIZE_ERRORS):
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 268, in __setitem__
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 221, in __setitem__
"""Get SQL parameter marks for a sequence-based query, and ensure value is a sequence"""
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/Avasam/mysite/backend/./services/utils.py", line 363, in start_and_wait_for_threads
future.result()
File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 438, in result
return self.__get_result()
File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
raise self._exception
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/Avasam/mysite/backend/./services/user_updater.py", line 123, in set_points_thread
__set_run_points(run)
File "/home/Avasam/mysite/backend/./services/user_updater.py", line 186, in __set_run_points
leaderboard = get_file(url, params, True)
File "/home/Avasam/mysite/backend/./services/utils.py", line 198, in get_file
response = get_request_cache_bust_if_disk_quota_exceeded()
File "/home/Avasam/mysite/backend/./services/utils.py", line 183, in get_request_cache_bust_if_disk_quota_exceeded
response = session.get(url, params=params, headers=headers)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
return self.request('GET', url, **kwargs)
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/session.py", line 115, in request
cache_key=cache_key,
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/session.py", line 147, in send
return response
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/session.py", line 193, in _send_and_cache
cache_criteria = {
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/backends/base.py", line 97, in save_response
except (KeyError, *DESERIALIZE_ERRORS):
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 268, in __setitem__
File "/home/Avasam/.local/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 221, in __setitem__
"""Get SQL parameter marks for a sequence-based query, and ensure value is a sequence"""
sqlite3.OperationalError: database is locked
```

**Comment by JWCook** [comment]
Is this in a multi-threaded or multi-process application? If so, the [docs](https://requests-cache.readthedocs.io/en/stable/session.html#requests_cache.session.CachedSession.cache_disabled) do mention that `CachedSession.cache_disabled()` is not thread-safe.

I think that making that thread-safe on the library side would be more complicated than just putting a lock around it, but there could be a good solution that I'm just not thinking of at the moment.

Currently, if you're multi-threading and have a request that you always want to skip the cache, using a regular `requests.Session` for that request is the best option.

Another possible option would be to add another argument to `CachedSession.request()` (and other request functions) that skips reading from the cache.

**Comment by Avasam** [comment]
> Currently, if you're multi-threading and have a request that you always want to skip the cache, using a regular requests.Session for that request is the best option.

This is basically what I went for.
```py
session = CachedSession(
    expire_after=timedelta(days=1),
    allowable_codes=(200, 500),
    ignored_parameters=["status", "video-only", "embed"],
    backend=configs.cached_session_backend,
    fast_save=True,
    use_temp=True)
uncached_session = Session()
# [...]
# `cached` is a function parameter
    try:
        response = (session if cached else uncached_session).get(url, params=params, headers=headers)
    # Note: This happens with LOTS of concurent requests
    except OperationalError as error:
        print("Ignoring cache for this request because of OperationalError:", error)
        response = uncached_session.get(url, params=params, headers=headers)
```

I'm fine if you consider this to be the intended solution.

**Comment by JWCook** [comment]
> I'm fine if you consider this to be the intended solution.

Yes, that's the best option at the moment. I'm definitely open to PRs if anyone else has ideas on how to make that thread-safe. And I made a separate issue for adding an option to skip reading from the cache: #539
