### ISSUE TITLE
`pymongo (3.0.3)` does not have `Connection` class

### ISSUE THREAD

**Issue by char101** [reclosedev/requests-cache#53]
```
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests_cache.backends.mongo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/projects/citation/env/lib/python3.4/site-packages/requests_cache/backends/mongo.py", line 10, in <module>
    from .storage.mongodict import MongoDict, MongoPickleDict
  File "/root/projects/citation/env/lib/python3.4/site-packages/requests_cache/backends/storage/mongodict.py", line 15, in <module>
    from pymongo import Connection
ImportError: cannot import name 'Connection'
>>> import pymongo
>>> dir(pymongo)
['ALL', 'ASCENDING', 'CursorType', 'DESCENDING', 'DeleteMany', 'DeleteOne', 'GEO2D', 'GEOHAYSTACK', 'GEOSPHERE', 'HASHED', 'IndexModel', 'InsertOne', 'MAX_SUPPORTED_WIRE_VERSION', 'MIN_SUPPORTED_WIRE_VERSION', 'MongoClient', 'MongoReplicaSetClient', 'OFF', 'ReadPreference', 'ReplaceOne', 'ReturnDocument', 'SLOW_ONLY', 'TEXT', 'UpdateMany', 'UpdateOne', 'WriteConcern', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_cmessage', 'auth', 'bulk', 'client_options', 'collection', 'command_cursor', 'common', 'cursor', 'cursor_manager', 'database', 'errors', 'get_version_string', 'has_c', 'helpers', 'ismaster', 'message', 'mongo_client', 'mongo_replica_set_client', 'monitor', 'monotonic', 'network', 'operations', 'periodic_executor', 'pool', 'read_preferences', 'response', 'results', 'server', 'server_description', 'server_selectors', 'server_type', 'settings', 'son_manipulator', 'ssl_support', 'thread_util', 'topology', 'topology_description', 'uri_parser', 'version', 'version_tuple', 'write_concern']
```

**Comment by char101** [comment]
Workaround hack by patching `pymongo`

```python
import pymongo
pymongo.Connection = None
import requests_cache
```

**Comment by jagguli** [comment]
thanks.

**Comment by chengguangnan** [comment]
How come that is a hack? I think we would need to update the code to be compatible with the latest pymongo driver.

**Comment by chengguangnan** [comment]
This is a workaround:

`pip install pymongo==2.7.2
`

**Comment by char101** [comment]
This is a clearly a bug about requests-cache not working with pymongo 3.x not 2.x, so how come installing pymongo=2.x version a workaround?

**Comment by chengguangnan** [comment]
What bug? I think it's just incompatible with version 3. I have no problem of using it with pymongo v2.7.2.

**Comment by char101** [comment]
`reclosedev added the bug label on Mar 19`

**Comment by char101** [comment]
Just to be clear, no one is talking about pymongo 2.x here. I know it works with pymongo 2.x.
