### ISSUE TITLE
Array as a JSON root is not supported 

### ISSUE THREAD

**Issue by pkrefta** [reclosedev/requests-cache#536]
### The problem
If specific URL returns JSON and root object is an array it causes anexception

```
Invalid JSON body:
Traceback (most recent call last):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/ec-QLVbNtLr-py3.9/lib/python3.9/site-packages/requests_cache/cache_keys.py", line 170, in normalize_json_body
    body = filter_sort_dict(body, ignored_parameters)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/ec-QLVbNtLr-py3.9/lib/python3.9/site-packages/requests_cache/cache_keys.py", line 213, in filter_sort_dict
    return dict(sorted(data.items()))
AttributeError: 'list' object has no attribute 'items'
```
According to JSON spec array is a valid root.

### Expected behavior
It should properly cache the request.

### Workarounds
I'm using an external API so I cannot avoid this.

### Environment
- requests-cache version: 0.9.2
- Python version: 3.9.1
- Platform: MacOS

**Comment by JWCook** [comment]
Thanks for reporting that. I'll get that fixed soon.

**Comment by JWCook** [comment]
Fixed! This will be included in the next patch release.

**Comment by pkrefta** [comment]
Great - thank you 👏
