### ISSUE TITLE
Request throttling example is broken in Python 3

### ISSUE THREAD

**Issue by danvk** [reclosedev/requests-cache#62]
I added `()` to the `print` statement in the throttling example here:
https://requests-cache.readthedocs.org/en/latest/user_guide.html#usage

(see https://gist.github.com/danvk/f8c4d9d5cf9fde627ebb)

I'm getting this error:

```
$ python cache-issue.py
Traceback (most recent call last):
  File "cache-issue.py", line 23, in <module>
    s.get('http://httpbin.org/delay/get')
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/requests_cache/core.py", line 126, in request
    **kwargs
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/requests_cache/core.py", line 99, in send
    return send_request_and_cache_response()
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/requests_cache/core.py", line 91, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/requests/sessions.py", line 582, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/Users/danvk/.virtualenvs/osm-segments/lib/python3.5/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
TypeError: hook() got an unexpected keyword argument 'proxies'
```

I'm using `requests` 2.9.1 and `requests_cache` 0.4.12.

**Comment by reclosedev** [comment]
Thanks! Hook accepts additional arguments in new ``requests`` versions. 
http://docs.python-requests.org/en/master/user/advanced/#event-hooks

I've updated example in documentation.
