### ISSUE TITLE
Some unexpected error with cattrs 22.1.0

### ISSUE THREAD

**Issue by carlosal1015** [reclosedev/requests-cache#661]
Hi dear @JWCook, I am experimenting an unexpected behaviour, not necessarily a bug, but

### The problem
[`python-cattrs 22.1.0`](https://archlinux.org/packages/community/any/python-cattrs) was upgraded today and now we can not run the `check()` function here

```python
==> Starting check()...
No module named 'exceptiongroup'
Traceback (most recent call last):
  File "/tmp/makepkg/python-requests-cache-git/src/requests-cache/requests_cache/__init__.py", line 9, in <module>
    from .backends import *
  File "/tmp/makepkg/python-requests-cache-git/src/requests-cache/requests_cache/backends/__init__.py", line 7, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/tmp/makepkg/python-requests-cache-git/src/requests-cache/requests_cache/backends/base.py", line 22, in <module>
    from ..serializers import SERIALIZERS, SerializerPipeline, SerializerType, pickle_serializer
  File "/tmp/makepkg/python-requests-cache-git/src/requests-cache/requests_cache/serializers/__init__.py", line 24, in <module>
    from .cattrs import CattrStage
  File "/tmp/makepkg/python-requests-cache-git/src/requests-cache/requests_cache/serializers/cattrs.py", line 19, in <module>
    from cattr import GenConverter
  File "/usr/lib/python3.10/site-packages/cattr/__init__.py", line 1, in <module>
    from .converters import Converter, GenConverter, UnstructureStrategy
  File "/usr/lib/python3.10/site-packages/cattr/converters.py", line 1, in <module>
    from cattrs.converters import Converter, GenConverter, UnstructureStrategy
  File "/usr/lib/python3.10/site-packages/cattrs/__init__.py", line 1, in <module>
    from cattr import converters, disambiguators, dispatch, errors, gen, preconf
  File "/usr/lib/python3.10/site-packages/cattr/disambiguators.py", line 15, in <module>
    from cattrs._compat import get_origin
  File "/usr/lib/python3.10/site-packages/cattrs/_compat.py", line 38, in <module>
    from exceptiongroup import ExceptionGroup
ModuleNotFoundError: No module named 'exceptiongroup'
ImportError while loading conftest '/tmp/makepkg/python-requests-cache-git/src/requests-cache/tests/conftest.py'.
tests/conftest.py:28: in <module>
    from requests_cache import ALL_METHODS, CachedSession, install_cache, uninstall_cache
E   ImportError: cannot import name 'ALL_METHODS' from 'requests_cache' (/tmp/makepkg/python-requests-cache-git/src/requests-cache/requests_cache/__init__.py)
==> ERROR: A failure occurred in check().
    Aborting...
```

### Expected behavior

[All the test must be pass excepted integration tests that were disabled](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-requests-cache-git#n46).

### Steps to reproduce the behavior

Install `python-url-normalize` from AUR, then
```
git clone https://aur.archlinux.org/python-requests-cache-git.git
cd python-requests-cache-git
makepkg -s
```

### Workarounds

Researching, not workaround from my side.

### Environment
- requests-cache version: main (last commit) [python-requests-cache-git](https://aur.archlinux.org/packages/python-requests-cache-git) from AUR.
- Python version: `3.10.5`
- Platform: Arch Linux

Meow.

Thanks.

**Comment by JWCook** [comment]
Also added an issue on the cattrs repo for reference: https://github.com/python-attrs/cattrs/issues/280
