### ISSUE TITLE
requests_cache.disabled() not working with sessions

### ISSUE THREAD

**Issue by xocoatzin** [reclosedev/requests-cache#75]
The following code fails:

```
s = requests.Session()
s.auth = ('####', '-')
s.headers.update({'User-Agent': 'XYZ'})

#...

with requests_cache.disabled():
    r = s.get(url, stream=True)
```

`url` returns a 302 to a signed URL in Cloud Storage. It fails when the referenced file is large (this was 800 Mb or so)

**The disturbing part is that the traceback shows that the cache is not actually being disabled**. 
I fixed it by changing `s.get()` to `requests.get()`.

```
Traceback (most recent call last): 
  File "/lib/recording_processor.py", line 464, in get_single_file
    r = self.s.get(url, stream=True)
  File "/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/requests_cache/core.py", line 126, in request
    **kwargs
  File "/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/venv/local/lib/python2.7/site-packages/requests_cache/core.py", line 99, in send
    return send_request_and_cache_response()
  File "/venv/local/lib/python2.7/site-packages/requests_cache/core.py", line 91, in send_request_and_cache_response
    response = super(CachedSession, self).send(request, **kwargs)
  File "/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 179, in resolve_redirects
    **adapter_kwargs
  File "/venv/local/lib/python2.7/site-packages/requests_cache/core.py", line 99, in send
    return send_request_and_cache_response()
  File "/venv/local/lib/python2.7/site-packages/requests_cache/core.py", line 93, in send_request_and_cache_response
    self.cache.save_response(cache_key, response)
  File "/venv/local/lib/python2.7/site-packages/requests_cache/backends/base.py", line 46, in save_response
    self.responses[key] = self.reduce_response(response), datetime.utcnow()
  File "/venv/local/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 160, in __setitem__
    sqlite.Binary(pickle.dumps(item)))
  File "/venv/local/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py", line 125, in __setitem__
    self.table_name, (key, item))
InterfaceError: Error binding parameter 1 - probably unsupported type.
```

**Comment by reclosedev** [comment]
``request_cache.disabled`` works by reverting ``requests.Session`` monkey-patch. So it works only for new instances (which are created in ``requests.get``, etc). 

For you own session, you can use [``CachedSession.cache_disabled()``](http://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.core.CachedSession.cache_disabled) context manager:
```python
s = requests.Session()
# ...
with s.cache_disabled():
    r = s.get(url, stream=True)
```
I'll update docs.
